### PR TITLE
Create SimplePlotter_withMotor.ino

### PR DESCRIPTION
**Pull request by LeandroLimaPRO**
added example with command of and linear x and y coordinates in millimeter

### CODE REVIEW

**Comment by tinkersprojects** [comment]
Look great, I will test it soon.
I may change home to Incremental Mode with g-code G2 since home is not doing anything.

**Comment by LeandroLimaPRO** [comment]
code G is up to the user's discretion

**Comment by tinkersprojects** [comment]
yea i know. i will probs just remove the home(), it does not do anything. Incremental Mode may confuse people.

**Comment by LeandroLimaPRO** [comment]
truth

**Comment by LeoVerheyden** [comment]
Can this work with 6 axis  ? If yes what are the changes to do ?  Thanks

**Comment by LeandroLimaPRO** [comment]
Hello, of course you can, but be aware of adding the corresponding ports to the other 4 axes, the DIR and STEP. There is and change the function 

> "void gotoLocation (double x, double y)"

and 

> "void moviment ()"

**Comment by tinkersprojects** [comment]
hey @LeoVerheyden, this library is just a Gcode reader/interpreter and then it's up to you to add the motor controllers. This example shows how the can be used with stepper motors. The example is for 2 axis currently. 
like @LeandroLimaPRO was saying, you will need to change those functions and you will also need to know how the 6 axis will be controlled. X in the gcode is for the x axis, Y in the gcode is for the x axis not sure which letter you will need to use for the others. you will probs use X,Y,Z,A,B,C or something like that. A is sometimes used for other things.

**Comment by LeoVerheyden** [comment]
And it works !!! with accelstepper and flexystepper on arduino

**Comment by tinkersprojects** [comment]
i have not heard of flexystepper, i will look into it. 
if you have any other problems, let us know.

**Comment by LeoVerheyden** [comment]
is it also possible to tkane M commandes  and  T commandes ???

**Comment by tinkersprojects** [comment]
you can use any letter commands from A-Z (if you use lover case it will convert it to upper case)

 if its an action command like homing you can add it to:
`commandscallback commands[1] = {{"G28",homing},{"M36",OtherMFunction},{"T67",OtherTFunction}};`
note: homing, OtherMFunction, OtherTFunction are functions and need to be decleared above this line

if its to get a value, you can use the following to get the value:
`Mvalue = Commands.GetValue('M');`

**Comment by LeoVerheyden** [comment]
Hi   , I tried with 5 stepper motors at once and they turn !!!! 
If I send a command to the seriel port  G0 X100 Y100 Z100 A12 B52  it turns to the position ( I have to test if ist ok with the right position) . Problem is if I send a new command on the serial port  like  M01  he is doing the same as  G0 X100 Y100 Z100 A12 B52  . Do you have an idea what I am doing wrong  ?

**Comment by tinkersprojects** [comment]
yea, i added a clear buffer and did not add it to this program. i will add and debug this program. i have been very busy.
if you want come chat on discord: https://discord.gg/MRPFpb

**Pull request merged**
