### PR TITLE
Command identifiers should be in capitals

### PR DESCRIPTION
**Pull request by MrSeccubus**

### CODE REVIEW

**Comment by LeandroLimaPRO** [comment]
I don't recommend polluting the library with strings, especially print or println, because the data load will be bigger and one for example will have its memory overflowed.

**Comment by tinkersprojects** [comment]
Its a good idea but since this library can run through the serial I don't think it will work.
what could work is move code like that to a DEBUG mode.
having all the print and println between:
```c++
#if (DEBUG_G ==1)
// code
#endif
```

**Comment by MrSeccubus** [comment]
Crap! That merge did not go as Intended. I’ll open another PR that is correct.

**Comment by tinkersprojects** [comment]
All good, if you want to talk about it more there is a link to the discord
server on the home page of my website

Regards,
William Bailes
https://tinkersprojects.com

**Pull request closed without merging**
